name: Execute all the test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
    - 'parser/'
    - '.github/workflows/build.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'parser'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.1'
    - run: go test
